# This is a basic workflow to help you get started with Actions
name: SwiftLint

on:
  pull_request:
    branches: [ main ]

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
