name: Unit_Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and run tests of ContentPassExample
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: xcodebuild test -scheme ContentPassExample -workspace ContentPassExample/ContentPassExample.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' | xcpretty && exit ${PIPESTATUS[0]}